### ISSUE TITLE
Failed copy from word.

### ISSUE THREAD

**Issue by liuxiawei** [CrossPaste/crosspaste-desktop#2029]
### How frequently does the bug occur?

-- select --

### Description

Crosspatse is amazing！感谢大佬为此的付出！但我在近日使用中发现了新的BUG。
从word（office2016 专业增强版）中复制富文本时，在crosspaste中显示为未知图片，不能正常显示，不能正常打开，可以正常粘贴。
在PowerPoint中复制富文本显示为透明背景图片，显示不完全，可以正常粘贴，
图片双击后打开，没有替换粘贴板，与其他逻辑不一致（文本双击是直接替换粘贴板，在我上次建议中添加直接粘贴）。
![40860c36-1011-4c2b-aa5f-5e7619c00f7c](https://github.com/user-attachments/assets/8bfd0823-8c2b-4d99-91ef-a16562efae64)
在linuxWPS下富文本能正常识别为带格式文本，但直接复制文本框无法正常识别
以上提到的BUG主要在word、wps套件系列中的应用，在copyQ中能正常使用，所以怀疑存在BUG，感谢您的付出！

### Can you reproduce the bug?

-- select --

### Version

1.0.11(1037)

### OS

Win10Pro

**Comment by guiyanakuang** [comment]
@liuxiawei. Thank you for reporting this issue. I will reproduce it when I have time and investigate how to resolve it.

**Comment by guiyanakuang** [comment]
I've conducted extensive testing and found the following:

1. When directly copying rich text, pasting works as expected.
2. When copying a text box component from Office software, the clipboard contains an image generated from that component. In this case, CopyQ behaves the same way as you described.
3. If you try to paste into a text box in this scenario, only a randomly generated image filename is pasted, rather than the actual text content.

**Comment by guiyanakuang** [comment]
I think the reason double-clicking doesn't paste is that in the image clipboard interface, double-clicking opens the image instead of pasting across applications. This issue will be addressed in a future update.

**Comment by guiyanakuang** [comment]
@liuxiawei. We've released version 1.0.12.1077, which includes improvements to the Office clipboard functionality. RTF format support has been added. This update should address the issue you reported. Please test it and let us know if it resolves your issue.

**Comment by liuxiawei** [comment]
Great work! Thanks for your help. And hope this app develop more better!
